name = "archlight"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true

routes = [
  { pattern = "supjavmissavsextb.dpdns.org", custom_domain = true, zone_id = "308d61c78cb17494013ba7b32dc344b1" },
  { pattern = "ava.game.naver.com.vm.gpj.web.id", custom_domain = true, zone_id = "308d61c78cb17494013ba7b32dc344b1" },
  { pattern = "df.game.naver.com.vm.gpj.web.id", custom_domain = true, zone_id = "308d61c78cb17494013ba7b32dc344b1" },
  { pattern = "graph.instagram.com.vm.gpj.web.id", custom_domain = true, zone_id = "308d61c78cb17494013ba7b32dc344b1" },
  { pattern = "zaintest.vuclip.com.vm.gpj.web.id", custom_domain = true, zone_id = "308d61c78cb17494013ba7b32dc344b1" },
  { pattern = "support.zoom.us.vm.gpj.web.id", custom_domain = true, zone_id = "308d61c78cb17494013ba7b32dc344b1" },
  { pattern = "cache.netflix.com.vm.gpj.web.id", custom_domain = true, zone_id = "308d61c78cb17494013ba7b32dc344b1" },
  { pattern = "api24-normal.tiktokv.com.vm.gpj.web.id", custom_domain = true, zone_id = "308d61c78cb17494013ba7b32dc344b1" }
]

[[kv_namespaces]]
binding = "library"
id = "a9f61fcc3abf48af91a5924027ee1a1a"

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]

UUID = "38425afe-8466-4876-8223-f3d604ca3c18"

MAIN_PAGE_URL = "https://raw.githubusercontent.com/hoshiyomiX/ArchLight/refs/heads/master/web/index.html"
SUB_PAGE_URL  = "https://raw.githubusercontent.com/hoshiyomiX/ArchLight/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/hoshiyomiX/ArchLight/refs/heads/master/web/link.html"
CONVERTER_PAGE_URL = "https://raw.githubusercontent.com/hoshiyomiX/ArchLight/refs/heads/master/web/converter.html"
CHECKER_PAGE_URL = "https://raw.githubusercontent.com/hoshiyomiX/ArchLight/refs/heads/master/web/checker.html"
